### ISSUE TITLE
Git doesn't like UTF-16

### ISSUE THREAD

**Issue by erik-am** [Cyan-Inc/ObductionFanLocalization#1]
According to the README instructions, translation files should be saved as UTF-16 encoding.
I made sure I did, but unfortunately `git diff` doesn't support UTF-16 and starts treating the files as binary.

This also makes changes in pull requests hard to review, because you'll see this on GitHub if you made changes to a file:
![utf16](https://cloud.githubusercontent.com/assets/2051896/19212762/959e814a-8d58-11e6-88bb-c49778a6df72.PNG)

Is it perhaps an idea to use UTF-8 on GitHub and then convert it to UTF-16 when adding the files to the game? Or is UTF-8 too limited to support all the languages?

**Comment by hgamiel** [comment]
Another programmer on the team and I spoke about this recently. I should have added into the README/updated it to reflect the steps required for the PR so that there isn't any confusion about that.

Our system for localization in the engine prefers UTF-16 files. We have come across issues in some languages translated for the game in which the files were in UTF-8 format and displayed character issues in-game.

Unfortunately, like you said, that does mean that the files will be listed as binary files when diffed with git. It'll have to do in the meantime. We're going to look into alternative, reliable solutions, but UTF-16 files for this repo will be what we accept in the meantime.
